services:
  app:
    image: php:apache
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:rw
    environment:
      PAYPAL_API_URL: https://api-m.sandbox.paypal.com/
    ports:
      - 80:80
  composer:
    image: composer:latest
    working_dir: /tmp/composer
    volumes:
      - .:/tmp/composer:rw
    entrypoint:
      - composer
      - --ignore-platform-reqs
